[package]
name = "daemonseed-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license = "AGPL-3.0-or-later"
description = "daemonseed protocol library"

[dependencies]
oxicrypt-module = { workspace = true }
oxicrypt-sha = { workspace = true }
oxicrypt-kdf = { workspace = true }
oxicrypt-aes = { workspace = true }
oxicrypt-ml-dsa = { workspace = true }
oxicrypt-ml-kem = { workspace = true }
bip39 = { workspace = true }
zeroize = { workspace = true }
uuid = { workspace = true }
hex = { workspace = true }
getrandom.workspace = true
zxcvbn.workspace = true
unicode-normalization.workspace = true
toml = { workspace = true }
serde = { workspace = true }
argon2.workspace = true
tokio = { workspace = true }
prost = { workspace = true }
daemonseed-proto = { path = "../daemonseed-proto" }
redb = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
