[package]
name = "daemonseed-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license = "AGPL-3.0-or-later"
description = "daemonseed protocol library"

[dependencies]
oxicrypt-module = { workspace = true }
oxicrypt-sha = { workspace = true }
bip39 = { workspace = true }
zeroize = { workspace = true }
hex = { workspace = true }
getrandom.workspace = true
